version: '3'
services:

  db:
    image:
      mysql:5.7
    environment:
      MYSQL_DATABASE: homesearch
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
   volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
